version: '3'

services:
  streamlit:
    image: app
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    networks:
      - project-network

networks:
  project-network:
    external: true